"""Generate the PyInstaller version resource from ``src/version.py``.

The application reads ``ProductVersion`` out of its own executable to decide
whether an update is available, so the resource written here and
``src/version.py`` must always agree.  Generating the file (instead of
hand-editing ``file_version_info.txt``, which is git-ignored) keeps them in
sync.

Usage::

    python build_tools/make_version_info.py [output_path]
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from version import GITHUB_REPOSITORY, __version__, version_info_tuple  # noqa: E402

DEFAULT_OUTPUT = os.path.join(ROOT, "build", "version_info.txt")

VERSION_TEMPLATE = """# UTF-8
#
# Generated by build_tools/make_version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [StringStruct('CompanyName', 'Hushmix'),
           StringStruct('FileDescription', 'Hushmix - application volume mixer'),
           StringStruct('FileVersion', '{version}'),
           StringStruct('InternalName', 'Hushmix'),
           StringStruct('LegalCopyright', 'MIT License'),
           StringStruct('OriginalFilename', 'Hushmix.exe'),
           StringStruct('ProductName', 'Hushmix'),
           StringStruct('ProductVersion', '{version}'),
           StringStruct('Comments', 'https://github.com/{repository}')])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version_info(output_path=DEFAULT_OUTPUT, version=None):
    """Write the version resource file and return its path."""
    version = version or __version__
    version_tuple, _padded = version_info_tuple()
    # Windows expects a four-part version; keep the resource textual value in
    # that form so the updater can compare it as a normal version string.
    textual = ".".join(str(part) for part in version_tuple)

    content = VERSION_TEMPLATE.format(
        version=textual,
        version_tuple=tuple(version_tuple),
        repository=GITHUB_REPOSITORY,
    )

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="\n") as stream:
        stream.write(content)

    return output_path


def main():
    output = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUTPUT
    path = write_version_info(output)
    print(f"Wrote version resource for {__version__} to {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
